# .scrutinizer.yml
tools:
  external_code_coverage:
    runs: 3 # wait for 3 submitions, 5.6, 7.0, 7.1
checks:
  php:
    code_rating: true
    duplication: true
  python:
    code_rating: true
    duplicate_code: true
