language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2.24
  - 7.3.11

services:
  - redis-server
  - mysql

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini ; fi
  - travis_retry composer self-update --stable -n

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable

before_script:
  - cp .env.travis .env
  - mysql -e 'create database smartsettia;'
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan migrate
  - php artisan db:seed
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi

after_script:
  - ls -laR storage
  - cat storage/logs/*
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
